# Generated by Django 2.2.7 on 2020-01-15 04:40

import json
import re

from django.db.utils import IntegrityError
from django.db import migrations
from django.db import transaction


def create_minerals(apps, schema_editor):
    Mineral = apps.get_model('minerals', 'Mineral')
    with open('minerals/minerals.json', 'r', encoding='utf-8') as data_file:
        uploaded_minerals_data = json.load(data_file)
        for mineral_data in uploaded_minerals_data:
            name_keys = list(mineral_data.keys())
            for name in name_keys:
                key_value = mineral_data.pop(name)
                new_name = re.sub(r'\s', '_', name)

                if new_name == 'image_filename':
                    mineral_data[new_name] = f"{mineral_data['name']}.jpg"
                else:
                    mineral_data[new_name] = key_value
            try:
                with transaction.atomic():
                    Mineral.objects.create(**mineral_data)
            except IntegrityError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_minerals)
    ]
